theme: jekyll-theme-dinky
# Site settings
title: Jenna Petersen
description: "This is my first trial github page"
url: "http://Jenna-P.github.io"

github_username:  Jenna-P
facebook_username: Jenna Bokyung S
email: jenn2464@edu.easj.dk




